import type {Metadata} from "next";
import {Inter, Lora, Montserrat_Subrayada, Roboto} from "next/font/google";
import {ClerkProvider} from "@clerk/nextjs";
import "./globals.css";
import ToastProvider from "@/components/provider/provider-toast";
import React from "react";
import {ConfettiProvider} from "@/components/provider/confetti-provider";

const inter = Inter({subsets: ["latin"]});
const lora = Lora({subsets: ["latin"]})
const roboto = Roboto({weight: "400", subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Akmp Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider afterSignOutUrl={'/'}>
        <html lang="en" className={"scroll-smooth"}>
        <body className={inter.className}>
        <ConfettiProvider/>
        <ToastProvider/>
        {children}
        </body>
        </html>
      </ClerkProvider>
  );
}
